[DDIM_SAMPLER]
beta_schedule = "linear"
beta_start = 0.0001
beta_end = 0.02
total_timesteps = 1000

[DDPM_SAMPLER]
beta_schedule = "linear"
timesteps = 1000
beta_start = 0.0001
beta_end = 0.02

[DDPM_UNET]
[DDPM_UNET.backend]
type = "tensorrt"
model_file_path = "../weights/diffusion/ldm/latent_ddpm_celeba-hq.engine"
device = "gpu"
