[LDM_SAMPLER]
vae_decoder_cfg="../conf/model/diffusion/ldm/autoencoder_kl.toml"
latent_diffusion_cfg="../conf/model/diffusion/ldm/latent_diffusion.toml"
latent_dims=4
downscale=8
latent_scale=0.18215
