[DINOV2]
[DINOV2.backend]
type = "mnn"
model_file_path = "../weights/classification/dinov2/dinov2_vits14_pretrain.mnn"
device = "gpu"
threads = 4
input_layout = "nchw"
precision_mode = 0
power_mode = 0

[DINOV2.params]
pooling = "cls"
# normalize = false
