[LIBFACE]
[LIBFACE.backend]
type = "mnn"
model_file_path = "../weights/object_detection/libfacedetection/face_detection_320x240_model.model"
device = "gpu"
threads = 4
precision_mode = 0
power_mode = 0
input_names = ["input"]
output_names = ["loc", "conf"]

[LIBFACE.params]
model_input_image_size = [320, 240]
model_score_threshold = 0.75
model_nms_threshold = 0.35
model_keep_top_k = 250
