[OPENAI_CLIP]

[OPENAI_CLIP.visual_backend]
type = "mnn"
model_file_path = "../weights/openai_clip/vit-b-32/visual.mnn"
device = "gpu"
threads = 4
precision_mode = 0
power_mode = 0
input_names = ["input"]
output_names = ["output"]

[OPENAI_CLIP.text_backend]
type = "mnn"
model_file_path = "../weights/openai_clip/vit-b-32/textual.mnn"
device = "gpu"
threads = 4
precision_mode = 0
power_mode = 0
input_names = ["input"]
output_names = ["output"]

[OPENAI_CLIP.params]
vocab_file_path = "../weights/openai_clip/vit-b-32/bpe_simple_vocab_16e6.txt"
context_length = 77
truncate_context = true
