[MSOCRNET]
model_file_path="../weights/scene_segmentation/msocrnet/msocrnet.mnn"
model_threads_num=4
model_input_image_size=[1024, 2048]
compute_backend="cuda"
backend_precision_mode=0
backend_power_mode=0
backend_type="onnx"

[MSOCRNET_ONNX]
model_file_path="../weights/scene_segmentation/msocrnet/msocrnet_fp16.onnx"
model_threads_num=4
model_input_image_size=[1024, 2048]
compute_backend="cuda"
gpu_device_id=0

[BACKEND_DICT]
mnn=0
onnx=1
