[MSOCRNET]
[MSOCRNET.backend]
type = "onnx"
model_file_path = "../weights/scene_segmentation/msocrnet/msocrnet_fp16.onnx"
device = "gpu"
device_id = 0
threads = 4

[MSOCRNET.params]
model_input_image_size = [1024, 2048]
