[ENLIGHTENGAN]
[ENLIGHTENGAN.backend]
type = "mnn"
model_file_path = "../weights/enhancement/enlighten_gan/enlightengan.model"
device = "cuda"
threads = 4
output_names = ["output"]
input_layout = "nchw"
precision_mode = 0
power_mode = 0

[ENLIGHTENGAN.params]
model_input_image_size = [256, 256]
