[BISENETV2]

[BISENETV2.backend]
type = "mnn"
model_file_path = "../weights/scene_segmentation/bisenetv2/bisenetv2_cityscapes.mnn"
device = "gpu"
threads = 4
input_layout = "nhwc"
input_names = ["input_tensor"]
output_names = ["final_output"]
precision_mode = 0
power_mode = 0
