[METRIC3D]
[METRIC3D.backend]
type = "tensorrt"
model_file_path = "../weights/mono_depth_estimation/metric3d/metric3d_750k_512x1088.engine"
device = "cuda"

[METRIC3D.params]
focal_length = 1000.0
# intrinsic fx fy cx cy
intrinsic = [1000.0, 1000.0, 256.0, 544.0]
canonical_size = [512, 960]
