[METRIC3D]
[METRIC3D.backend]
type = "tensorrt"
model_file_path = "../weights/mono_depth_estimation/metric3d/metric3d_750k_1088x1920.engine"
device = "gpu"

[METRIC3D.params]
focal_length = 1000.0
# intrinsic fx fy cx cy
intrinsic = [1000.0, 1000.0, 544.0, 960.0]
canonical_size = [512, 960]
