[DDIM_SAMPLER]
beta_schedule = "linear"
total_timesteps = 1000
beta_start = 0.0001
beta_end = 0.02
sample_size = [128, 128]
sample_steps = 50
channels = 3
eta = 1.0
cls_id = 0

[DDPM_UNET]
[DDPM_UNET.backend]
type = "onnx"
model_file_path = "../weights/diffusion/ddpm/cls_cond_ddpm_netease_album_cover_128x128.onnx"
device = "gpu"
device_id = 0
threads = 4
