[SUPERPOINT]
[SUPERPOINT.backend]
type = "mnn"
model_file_path = "../weights/feature_point/superpoint/superpoint_120x160.mnn"
device = "cuda"
threads = 4
input_layout = "nchw"
precision_mode = 0
power_mode = 0

[SUPERPOINT.params]
model_score_threshold = 0.015
model_nms_threshold = 4.0
max_track_length = 5
nn_dis_thresh = 0.02
