[PP_HUMANSEG]

[PP_HUMANSEG.backend]
type = "mnn"
model_file_path = "../weights/scene_segmentation/pphuman_seg/pp_humanseg_192x192_mobile.mnn"
device = "cuda"
threads = 4
input_layout = "nchw"
input_names = ["x"]
output_names = ["softmax_0.tmp_0"]
precision_mode = 0
power_mode = 0
