[ATTENTIVEGANDERAIN]
[ATTENTIVEGANDERAIN.backend]
type = "mnn"
model_file_path = "../weights/enhancement/attentive_gan_derain/attentive_gan_derain.model"
device = "cuda"
threads = 4
input_layout = "nhwc"
precision_mode = 0
power_mode = 0

[ATTENTIVEGANDERAIN.params]
model_input_image_size = [240, 320]
