[REALESRGAN]
[REALESRGAN.backend]
type = "mnn"
model_file_path = "../weights/enhancement/real_esrgan/realesr-general-x4v3.model"
device = "gpu"
threads = 4
input_layout = "nhwc"
precision_mode = 0
power_mode = 0
