#!/usr/bin/env bash
# mortredctl_init-edge.sh - generate a host-network Nginx config for Mortred.
#
# Nginx MUST share the host network namespace with Mortred (systemd unit or
# compose network_mode: host). A bridge container cannot reach 127.0.0.1:8080
# on the host.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="lan"
OUT=""
SERVER_NAME="localhost"
ENABLE_ADMIN=0
CERT=""
KEY=""
FORCE=0
UPSTREAM_INFER="127.0.0.1:8080"
UPSTREAM_ADMIN="127.0.0.1:8787"
LISTEN_TLS=443

while [ $# -gt 0 ]; do
    case "$1" in
        --mode) MODE="$2"; shift 2 ;;
        --out) OUT="$2"; shift 2 ;;
        --server-name) SERVER_NAME="$2"; shift 2 ;;
        --enable-admin) ENABLE_ADMIN=1; shift ;;
        --cert) CERT="$2"; shift 2 ;;
        --key) KEY="$2"; shift 2 ;;
        --force) FORCE=1; shift ;;
        --upstream) UPSTREAM_INFER="$2"; shift 2 ;;
        -h|--help)
            echo "usage: mortredctl init-edge --mode lan|acme|files [--out DIR] [--server-name NAME]"
            echo "                         [--enable-admin] [--cert CRT --key KEY] [--force]"
            exit 0
            ;;
        *) echo "[ERROR] unknown argument: $1" >&2; exit 1 ;;
    esac
done

case "$MODE" in
    lan|acme|files) ;;
    *) echo "[ERROR] --mode must be lan, acme, or files" >&2; exit 1 ;;
esac

OUT="${OUT:-$ROOT/conf/local/edge}"
if [ -f "$OUT/nginx.conf" ] && [ "$FORCE" -ne 1 ]; then
    echo "[ERROR] $OUT/nginx.conf exists; pass --force to regenerate" >&2
    exit 1
fi

SNIP="$ROOT/deploy/nginx/snippets"
PROXY="$(cat "$SNIP/proxy-to-mortred.conf")"
SSL_PARAMS="$(cat "$SNIP/ssl-params.conf")"
ACME="$(cat "$SNIP/acme-challenge.conf")"

mkdir -p "$OUT/tls"
umask 077

ssl_block=""
http80=""
case "$MODE" in
    lan)
        command -v openssl >/dev/null 2>&1 || { echo "[ERROR] openssl required for --mode lan" >&2; exit 1; }
        CA_KEY="$OUT/tls/ca.key"
        CA_PEM="$OUT/tls/ca.pem"
        SRV_KEY="$OUT/tls/server.key"
        SRV_CRT="$OUT/tls/server.crt"
        openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
            -subj "/CN=Mortred local CA" -keyout "$CA_KEY" -out "$CA_PEM" >/dev/null 2>&1
        openssl req -newkey rsa:2048 -sha256 -nodes -subj "/CN=$SERVER_NAME" \
            -keyout "$SRV_KEY" -out "$OUT/tls/server.csr" >/dev/null 2>&1
        openssl x509 -req -in "$OUT/tls/server.csr" -CA "$CA_PEM" -CAkey "$CA_KEY" \
            -CAcreateserial -out "$SRV_CRT" -days 825 -sha256 >/dev/null 2>&1
        rm -f "$OUT/tls/server.csr" "$OUT/tls/ca.srl"
        chmod 600 "$CA_KEY" "$SRV_KEY"
        chmod 644 "$CA_PEM" "$SRV_CRT"
        ssl_block="ssl_certificate tls/server.crt;
        ssl_certificate_key tls/server.key;
        $SSL_PARAMS"
        ;;
    files)
        [ -n "$CERT" ] && [ -n "$KEY" ] || { echo "[ERROR] --mode files requires --cert and --key" >&2; exit 1; }
        [ -f "$CERT" ] && [ -f "$KEY" ] || { echo "[ERROR] cert or key file missing" >&2; exit 1; }
        ssl_block="ssl_certificate $CERT;
        ssl_certificate_key $KEY;
        $SSL_PARAMS"
        ;;
    acme)
        LIVE="/etc/letsencrypt/live/$SERVER_NAME"
        ssl_block="ssl_certificate $LIVE/fullchain.pem;
        ssl_certificate_key $LIVE/privkey.pem;
        $SSL_PARAMS"
        mkdir -p /tmp/mortred-acme-placeholder
        http80="
    server {
        listen 80;
        listen [::]:80;
        server_name $SERVER_NAME;
        $ACME
        location / { return 301 https://\$host\$request_uri; }
    }"
        echo "  [note] acme mode expects: certbot certonly --webroot -w /var/www/mortred-acme -d $SERVER_NAME"
        echo "         then nginx -s reload. Do not use certbot --nginx (it rewrites this file)."
        ;;
esac

admin_server=""
if [ "$ENABLE_ADMIN" -eq 1 ]; then
    admin_server="
    server {
        listen $LISTEN_TLS ssl;
        listen [::]:$LISTEN_TLS ssl;
        server_name admin.$SERVER_NAME;
        $ssl_block
        location / {
            proxy_pass http://$UPSTREAM_ADMIN;
            $PROXY
        }
    }"
fi

cat >"$OUT/nginx.conf" <<EOF
# generated by mortredctl init-edge --mode $MODE — do not commit
worker_processes auto;
error_log stderr warn;
pid nginx.pid;
daemon off;

events { worker_connections 1024; }

http {
    default_type application/octet-stream;
    sendfile on;
    server_tokens off;
$http80
    server {
        listen $LISTEN_TLS ssl;
        listen [::]:$LISTEN_TLS ssl;
        server_name $SERVER_NAME;
        $ssl_block
        location / {
            proxy_pass http://$UPSTREAM_INFER;
            $PROXY
        }
    }
$admin_server
}
EOF
chmod 600 "$OUT/nginx.conf" 2>/dev/null || chmod 644 "$OUT/nginx.conf"

echo "== edge written: $OUT/nginx.conf (mode=$MODE) =="
echo "  upstream: http://$UPSTREAM_INFER"
if [ "$MODE" = "lan" ]; then
    echo "  trust CA once: $OUT/tls/ca.pem"
fi
echo "  test: nginx -t -p $OUT -c nginx.conf"
echo "  run:  nginx -p $OUT -c nginx.conf     # host network; Mortred on 127.0.0.1"
