#!/usr/bin/env bash
# mortredctl_init-trust.sh - generate machine-local identity (never commit).
#
# Writes conf/local/trust.env with four independent hex secrets:
#   MORTRED_GATEWAY_AUTH_TOKEN  inference
#   MORTRED_API_TOKEN           management
#   MORTRED_METRICS_TOKEN       Prometheus scrape
#   MORTRED_INTERNAL_TOKEN      gateway <-> model (optional override)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FORCE=0
OUT=""

while [ $# -gt 0 ]; do
    case "$1" in
        --force) FORCE=1; shift ;;
        --out) OUT="$2"; shift 2 ;;
        -h|--help)
            echo "usage: mortredctl init-trust [--force] [--out FILE]"
            echo "  writes conf/local/trust.env (mode 600); source it before start"
            exit 0
            ;;
        *) echo "[ERROR] unknown argument: $1" >&2; exit 1 ;;
    esac
done

OUT="${OUT:-$ROOT/conf/local/trust.env}"
mkdir -p "$(dirname "$OUT")"

if [ -f "$OUT" ] && [ "$FORCE" -ne 1 ]; then
    echo "[ERROR] $OUT exists; pass --force to rotate (old file is not overwritten otherwise)" >&2
    exit 1
fi

rand() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 24
        return
    fi
    dd if=/dev/urandom bs=24 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n'
    echo
}

infer="$(rand)"
admin="$(rand)"
scrape="$(rand)"
internal="$(rand)"
if [ "$infer" = "$admin" ] || [ "$scrape" = "$infer" ] || [ "$scrape" = "$admin" ]; then
    echo "[ERROR] generated colliding tokens; rerun" >&2
    exit 1
fi

umask 077
cat >"$OUT" <<EOF
# generated by mortredctl init-trust — do not commit
MORTRED_GATEWAY_AUTH_TOKEN=$infer
MORTRED_API_TOKEN=$admin
MORTRED_METRICS_TOKEN=$scrape
MORTRED_INTERNAL_TOKEN=$internal
EOF
chmod 600 "$OUT"

echo "== trust written: $OUT (mode 600) =="
echo "next:"
echo "  set -a && . $OUT && set +a"
echo "  docker compose: copy the three MORTRED_*_TOKEN values into the environment"
echo "  do not reuse scrape as inference or management"
