[FAST_SAM]
[FAST_SAM.backend]
type = "mnn"
model_file_path = "../weights/sam/fastsam_s/FastSAM-s.mnn"
device = "gpu"
threads = 4
input_layout = "nchw"
precision_mode = 0
power_mode = 0

[FAST_SAM.params]
conf_thresh = 0.4
iou_thresh = 0.9
