[SAM_AMG]

[SAM_AMG.encoder_backend]
type = "tensorrt"
model_file_path = "../weights/sam/mobile_sam/sm61/mobile_sam_encoder.engine"
device = "cuda"

[SAM_AMG.amg_decoder_backend]
type = "tensorrt"
model_file_path = "../weights/sam/mobile_sam/sm61/mobile_sam_amg_decoder.engine"
device = "cuda"

[SAM_AMG.params]
worker_queue_size = 8
compute_threads = -1
points_per_side = 32
pred_iou_thresh = 0.88
stability_score_thresh = 0.95
box_nms_thresh = 0.7
min_mask_region_area = 0
