[SAM_PREDICTOR]

[SAM_PREDICTOR.encoder_backend]
type = "mnn"
model_file_path = "../weights/sam/vit_l/sam_vit_l_encoder.mnn"
device = "gpu"
threads = 4
input_names = ["input_image"]
output_names = ["image_embeddings"]

[SAM_PREDICTOR.decoder_backend]
type = "onnx"
model_file_path = "../weights/sam/vit_l/sam_vit_l_decoder.onnx"
device = "gpu"
threads = 4
