[MODNET_MATTING]

[MODNET_MATTING.backend]
type = "mnn"
model_file_path = "../weights/matting/modnet/modnet_hrnet_w18.mnn"
device = "cuda"
threads = 4
input_layout = "nchw"
input_names = ["img"]
output_names = ["sigmoid_2.tmp_0"]
precision_mode = 0
power_mode = 0
